version: "3"
services:
  mariadb:
    build: .
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PWD=password
      - MYSQL_USER=foobar
      - MYSQL_USER_PWD=foobar
      - MYSQL_USER_DB=foobar
networks:
  default:
    external:
      name: proxy